# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
  set-executionpolicy Unrestricted
  write-host 'Installing Chocolatey'
  iex ((new-object net.webclient).DownloadString('http://chocolatey.org/install.ps1'))
  cinst 'git'
  if (-not (test-path ".ssh")) {
    mkdir .ssh
  }
  "github.com,192.30.252.131 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" | out-file ".ssh/known_hosts"
  if (-not (test-path -Path "devtools")) {
    git clone https://github.com/jamesandrewsmith/devtools.git devtools
  }
  cd devtools/windows
  git pull
  . "./install-package.ps1"
  foreach ($package in $args) {
    install-package($package)
  }
SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "windows8"
  config.vm.guest = :windows
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  
  config.vm.provider :vmware do |v|
     v.gui = true
     v.vmx["memsize"] = "9182"
     v.vmx["numvcpus"] = "2"
   end
   config.vm.network :forwarded_port, guest: 3389, host: 3389
   config.vm.network :forwarded_port, guest: 80, host: 8080
   config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
   config.windows.halt_timeout = 30
   config.winrm.username = "vagrant"
   config.winrm.password = "vagrant"

   config.vm.provision "shell" do |s|
    	s.inline = $script
    	s.args = [
    		"git"
    	]
	end
end
